# Generated by Django 2.2.4 on 2019-11-11 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20, verbose_name='Nombre Categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Equipo')),
                ('abreviacion', models.CharField(max_length=5, verbose_name='Abreviación Equipo')),
                ('logo_equipo', models.ImageField(upload_to='atebweb')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fecha', models.CharField(max_length=15, verbose_name='Nombre Fecha')),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha Publicacion')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('contenido', models.TextField(max_length=1000, verbose_name='Contenido')),
                ('resumen', models.TextField(max_length=300, verbose_name='Resumen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atebweb.Categoria')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateTimeField(verbose_name='Fecha de Partido')),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atebweb.Equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_2', to='atebweb.Equipo')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atebweb.Fecha')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='FotoPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='atebweb')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atebweb.Publicacion')),
            ],
            options={
                'verbose_name': 'Foto Publicacion',
                'verbose_name_plural': 'Fotos Publicaciones',
            },
        ),
    ]
