# Generated by Django 2.2.4 on 2019-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atebweb', '0002_fotogaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo_equipo',
            field=models.ImageField(upload_to='logoequipos'),
        ),
        migrations.AlterField(
            model_name='fotopublicacion',
            name='foto',
            field=models.ImageField(upload_to='fotopublicaciones'),
        ),
    ]
