# Generated by Django 2.2.4 on 2019-12-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atebweb', '0003_auto_20191130_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_4',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_5',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto_portada',
            field=models.ImageField(upload_to='fotopublicaciones'),
        ),
    ]
