# Generated by Django 2.2.4 on 2019-12-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atebweb', '0004_auto_20191203_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoPublicacion',
        ),
    ]
