# Generated by Django 2.2.4 on 2019-12-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atebweb', '0005_delete_fotopublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Video para Galería',
                'verbose_name_plural': 'Videos para Galería',
            },
        ),
    ]
